# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .project import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_v7_go.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_v7_go.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "v7-go",
  "mod": "index",
  "fqn": "pulumi_v7_go",
  "classes": {
   "v7-go:index:Project": "Project"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "v7-go",
  "token": "pulumi:providers:v7-go",
  "fqn": "pulumi_v7_go",
  "class": "Provider"
 }
]
"""
)
