// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace JamieDavenport.V7Go.Inputs
{

    public sealed class PropertyInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("propertyId", required: true)]
        public Input<string> PropertyId { get; set; } = null!;

        public PropertyInputArgs()
        {
        }
        public static new PropertyInputArgs Empty => new PropertyInputArgs();
    }
}
